SELECT * FROM customer_behaviour.customer;

use customer_behaviour;
select * from customer
limit 10;

/* Business Question */

-- Q1. What is the total revenue generated by male vs. female customers?
-- Q2. Which customers used a discount but still spent more than average purchase amount?
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- Q8. What are the top 3 most purchased products within each category?
-- Q9. Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue_generated
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than average purchase amount?

select customer_id,purchase_amount
from customer 
where discount_applied = 'Yes'
and purchase_amount > (select avg(purchase_amount)
                       from customer);

select avg(purchase_amount)
from customer;

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) as avg_product_rating
from customer 
group by item_purchased
order by avg_product_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer 
where shipping_type in('Express','Standard')
group by shipping_type;

/* Q5. Do subscribed customers spend more? Compare average spend and total revenue 
between subscribers and non-subscribers. */

select subscription_status, 
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue desc, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- simplification : calculate top 5 discount percentage for each product

select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 end)*100 / count(*),2) as discount_prcntg
from customer 
group by item_purchased 
order by discount_prcntg desc
limit 5;

/* Q7. Segment customers into New, Returning, and Loyal based on their total number 
  of previous purchases, and show the count of each segment. 
    1 -- New
  2-10 -- Returning
   10+ -- Loyal*/

select 
case when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
end as customer_segment,
count(*) as customer_count
from customer 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

with ranked_product as(
select item_purchased,category,
count(customer_id) as total_orders,
dense_rank() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by item_purchased,category)
select item_rank,
category,
item_purchased,
total_orders
from ranked_product
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe?

-- better approach

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

select
subscription_status,
count(case when previous_purchases > 5 then 1 end) as repeat_buyer_count
from customer 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?

select age_group,
round(sum(purchase_amount),2) as total_revenue,
round(sum(purchase_amount)*100 / (select sum(purchase_amount) from customer),2) as revenue_contri_prcntg
from customer
group by age_group
order by total_revenue desc, revenue_contri_prcntg desc;





  
